// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: audio_mixer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Fadeoff_Animation(lv_obj_t *TargetObject, int delay);
void Fadeon_Animation(lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Brightness
void ui_Brightness_screen_init(void);
lv_obj_t *ui_Brightness;
lv_obj_t *ui_Slider_group;
lv_obj_t *ui_Max;
lv_obj_t *ui_Min;
lv_obj_t *ui_Slider2;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_audio_wave_[1] = {&ui_img_audio_wave_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Fadeoff_Animation(lv_obj_t *TargetObject, int delay) {
  ui_anim_user_data_t *PropertyAnimation_0_user_data =
      lv_mem_alloc(sizeof(ui_anim_user_data_t));
  PropertyAnimation_0_user_data->target = TargetObject;
  PropertyAnimation_0_user_data->val = -1;
  lv_anim_t PropertyAnimation_0;
  lv_anim_init(&PropertyAnimation_0);
  lv_anim_set_time(&PropertyAnimation_0, 100);
  lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
  lv_anim_set_custom_exec_cb(&PropertyAnimation_0,
                             _ui_anim_callback_set_opacity);
  lv_anim_set_values(&PropertyAnimation_0, 255, 0);
  lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
  lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
  lv_anim_set_deleted_cb(&PropertyAnimation_0,
                         _ui_anim_callback_free_user_data);
  lv_anim_set_playback_time(&PropertyAnimation_0, 0);
  lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
  lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
  lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
  lv_anim_set_early_apply(&PropertyAnimation_0, true);
  lv_anim_start(&PropertyAnimation_0);
}
void Fadeon_Animation(lv_obj_t *TargetObject, int delay) {
  ui_anim_user_data_t *PropertyAnimation_0_user_data =
      lv_mem_alloc(sizeof(ui_anim_user_data_t));
  PropertyAnimation_0_user_data->target = TargetObject;
  PropertyAnimation_0_user_data->val = -1;
  lv_anim_t PropertyAnimation_0;
  lv_anim_init(&PropertyAnimation_0);
  lv_anim_set_time(&PropertyAnimation_0, 100);
  lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
  lv_anim_set_custom_exec_cb(&PropertyAnimation_0,
                             _ui_anim_callback_set_opacity);
  lv_anim_set_values(&PropertyAnimation_0, 0, 255);
  lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
  lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
  lv_anim_set_deleted_cb(&PropertyAnimation_0,
                         _ui_anim_callback_free_user_data);
  lv_anim_set_playback_time(&PropertyAnimation_0, 0);
  lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
  lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
  lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
  lv_anim_set_early_apply(&PropertyAnimation_0, true);
  lv_anim_start(&PropertyAnimation_0);
}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void brightness_ui_init(void) {
  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme = lv_theme_default_init(
      dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
      false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_Brightness_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_Brightness);
}
