// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: audio_mixer

#ifndef _AUDIO_MIXER_UI_H
#define _AUDIO_MIXER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void Fadeoff_Animation( lv_obj_t *TargetObject, int delay);
void Fadeon_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Brightness
void ui_Brightness_screen_init(void);
extern lv_obj_t *ui_Brightness;
extern lv_obj_t *ui_Slider_group;
extern lv_obj_t *ui_Max;
extern lv_obj_t *ui_Min;
extern lv_obj_t *ui_Slider2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_pot_ver_line_png);   // assets/pot_ver_line.png
LV_IMG_DECLARE( ui_img_pot_ver_knob_png);   // assets/pot_ver_knob.png
LV_IMG_DECLARE( ui_img_audio_wave_1_png);   // assets/audio_wave_1.png

LV_FONT_DECLARE( ui_font_14_bold);
LV_FONT_DECLARE( ui_font_mos_semibold_16);
LV_FONT_DECLARE( ui_font_number);

void brightness_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
