// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: audio_mixer

#include "ui.h"

void ui_Brightness_screen_init(void) {
  ui_Brightness = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Brightness, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_Brightness, lv_color_hex(0x2D2F36),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Brightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Slider_group = lv_obj_create(ui_Brightness);
  lv_obj_set_height(ui_Slider_group, 369);
  lv_obj_set_width(ui_Slider_group, lv_pct(100));
  lv_obj_set_x(ui_Slider_group, 0);
  lv_obj_set_y(ui_Slider_group, 20);
  lv_obj_set_align(ui_Slider_group, LV_ALIGN_TOP_MID);
  lv_obj_clear_flag(ui_Slider_group, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_Slider_group, lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Slider_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_main_stop(ui_Slider_group, 0,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Slider_group, 255,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_Slider_group, 0,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Max = lv_label_create(ui_Slider_group);
  lv_obj_set_width(ui_Max, 38);
  lv_obj_set_height(ui_Max, 19);
  lv_obj_set_x(ui_Max, 0);
  lv_obj_set_y(ui_Max, -20);
  lv_obj_set_align(ui_Max, LV_ALIGN_TOP_MID);
  lv_label_set_text(ui_Max, "MAX");
  lv_obj_set_style_text_color(ui_Max, lv_color_hex(0x9395A1),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Max, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_Max, LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Max, &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Min = lv_label_create(ui_Slider_group);
  lv_obj_set_width(ui_Min, 35);
  lv_obj_set_height(ui_Min, 19);
  lv_obj_set_x(ui_Min, 0);
  lv_obj_set_y(ui_Min, 20);
  lv_obj_set_align(ui_Min, LV_ALIGN_BOTTOM_MID);
  lv_label_set_text(ui_Min, "MIN");
  lv_obj_set_style_text_color(ui_Min, lv_color_hex(0x9395A1),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_Min, LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Min, &lv_font_montserrat_16,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Slider2 = lv_slider_create(ui_Slider_group);
  lv_slider_set_value(ui_Slider2, 30, LV_ANIM_OFF);
  if (lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE)
    lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
  lv_obj_set_width(ui_Slider2, 65);
  lv_obj_set_height(ui_Slider2, 289);
  lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
  lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Slider2, 255,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_pot_ver_line_png,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_Slider2, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_Slider2, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x50FF7D),
                            LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Slider2, 255,
                          LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_main_stop(ui_Slider2, 0,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Slider2, 255,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x50FF7D),
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_Slider2, 255,
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_width(ui_Slider2, 50,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_spread(ui_Slider2, 0,
                                 LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_radius(ui_Slider2, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x50FF7D),
                            LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_grad_stop(ui_Slider2, 255,
                                LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_pot_ver_knob_png,
                              LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x000000),
                                LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_Slider2, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_width(ui_Slider2, 30,
                                LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_spread(ui_Slider2, 0,
                                 LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_ofs_x(ui_Slider2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_ofs_y(ui_Slider2, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_Slider2, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_Slider2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_Slider2, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_Slider2, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_Slider2, 12, LV_PART_KNOB | LV_STATE_PRESSED);
  lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x50FF7D),
                            LV_PART_KNOB | LV_STATE_PRESSED);
  lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_PRESSED);
  lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x50FF7D),
                                LV_PART_KNOB | LV_STATE_PRESSED);
  lv_obj_set_style_shadow_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_PRESSED);
  lv_obj_set_style_shadow_width(ui_Slider2, 40,
                                LV_PART_KNOB | LV_STATE_PRESSED);
  lv_obj_set_style_shadow_spread(ui_Slider2, 0,
                                 LV_PART_KNOB | LV_STATE_PRESSED);
  lv_obj_set_style_shadow_ofs_x(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_PRESSED);
  lv_obj_set_style_shadow_ofs_y(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_PRESSED);
}
